<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BAN404 - Mandatory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="BAN404_files/libs/clipboard/clipboard.min.js"></script>
<script src="BAN404_files/libs/quarto-html/quarto.js"></script>
<script src="BAN404_files/libs/quarto-html/popper.min.js"></script>
<script src="BAN404_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BAN404_files/libs/quarto-html/anchor.min.js"></script>
<link href="BAN404_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BAN404_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BAN404_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BAN404_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BAN404_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#nessesary-libraries" id="toc-nessesary-libraries" class="nav-link active" data-scroll-target="#nessesary-libraries">Nessesary libraries</a></li>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link" data-scroll-target="#problem-1">Problem 1</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">a)</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">b)</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">c)</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">d)</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">e)</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">f)</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">g)</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">h)</a></li>
  </ul></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">a)</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">b)</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">c)</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">d)</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">e)</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BAN404 - Mandatory</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="nessesary-libraries" class="level2">
<h2 class="anchored" data-anchor-id="nessesary-libraries">Nessesary libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Ecdat)       <span class="co"># For the Wages dataset</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)     <span class="co"># For data visualization</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)       <span class="co"># For data manipulation</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)       <span class="co"># For data splitting, training, and cross-validation</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)      <span class="co"># For Ridge regression and LASSO</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)        <span class="co"># For generalized additive models (GAM)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)       <span class="co"># For regression trees</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)  <span class="co"># For plotting regression trees</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)        <span class="co"># For linear discriminant analysis (LDA)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest) <span class="co"># For random forest models, optional for advanced analysis</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="problem-1" class="level1">
<h1>Problem 1</h1>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">a)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Wages dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Wages)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore the structure of the dataset to identify potential predictors</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Wages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4165 obs. of  12 variables:
 $ exp    : int  3 4 5 6 7 8 9 30 31 32 ...
 $ wks    : int  32 43 40 39 42 35 32 34 27 33 ...
 $ bluecol: Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 2 2 2 ...
 $ ind    : int  0 0 0 0 1 1 1 0 0 1 ...
 $ south  : Factor w/ 2 levels "no","yes": 2 2 2 2 2 2 2 1 1 1 ...
 $ smsa   : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
 $ married: Factor w/ 2 levels "no","yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ sex    : Factor w/ 2 levels "female","male": 2 2 2 2 2 2 2 2 2 2 ...
 $ union  : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 2 ...
 $ ed     : int  9 9 9 9 9 9 9 11 11 11 ...
 $ black  : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
 $ lwage  : num  5.56 5.72 6 6 6.06 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of predictors you want to plot against lwage</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>selected_predictors1 <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">"smsa"</span>, <span class="st">"married"</span>, <span class="st">"sex"</span>, <span class="st">"union"</span>, <span class="st">"black"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>selected_predictors2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"exp"</span>, <span class="st">"wks"</span>, <span class="st">"bluecol"</span>, <span class="st">"ind"</span>, <span class="st">"south"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># "exp", "wks", "bluecol", "ind", "south", "smsa", "married", "sex", "union", "black"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plots_list1 <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>plots_list2 <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(predictor <span class="cf">in</span> selected_predictors1) {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  plots_list1[[predictor]] <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Wages, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(predictor), <span class="at">y =</span> lwage)) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"lwage vs."</span>, predictor), <span class="at">x=</span>predictor, <span class="at">y=</span><span class="st">"Log Wage"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(predictor <span class="cf">in</span> selected_predictors2) {</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  plots_list2[[predictor]] <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Wages, <span class="fu">aes</span>(<span class="at">x =</span> <span class="sc">!!</span><span class="fu">sym</span>(predictor), <span class="at">y =</span> lwage)) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"lwage vs."</span>, predictor), <span class="at">x=</span>predictor, <span class="at">y=</span><span class="st">"Log Wage"</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine and display the plots</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>combined_plot1 <span class="ot">&lt;-</span> <span class="fu">wrap_plots</span>(plots_list1, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>combined_plot2 <span class="ot">&lt;-</span> <span class="fu">wrap_plots</span>(plots_list2, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the combined plots</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>combined_plot1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>combined_plot2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose predictors "exp", "wks", "bluecol", "ind", "south", "smsa", "married", "sex", "union", "black"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>selected_predictors <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">"exp"</span>, <span class="st">"bluecol"</span>, <span class="st">"smsa"</span>, <span class="st">"married"</span>, <span class="st">"sex"</span>, <span class="st">"black"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Dynamically build the formula with polynomial terms for 'exp' and 'ed'</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>formula_str <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"lwage ~"</span>, <span class="fu">paste</span>(selected_predictors, <span class="at">collapse=</span><span class="st">" + "</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert string to formula</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(formula_str)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear regression model with polynomial terms</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula, <span class="at">data=</span>Wages)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = formula, data = Wages)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.06519 -0.24573  0.00082  0.24993  1.95602 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.1214614  0.0229699 266.499  &lt; 2e-16 ***
exp          0.0080701  0.0005508  14.651  &lt; 2e-16 ***
bluecolyes  -0.2872667  0.0122347 -23.480  &lt; 2e-16 ***
smsayes      0.1956731  0.0128705  15.203  &lt; 2e-16 ***
marriedyes   0.0892678  0.0223458   3.995 6.59e-05 ***
sexmale      0.4016828  0.0271981  14.769  &lt; 2e-16 ***
blackyes    -0.2155259  0.0237744  -9.065  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3814 on 4158 degrees of freedom
Multiple R-squared:  0.3182,    Adjusted R-squared:  0.3172 
F-statistic: 323.4 on 6 and 4158 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpret the model output</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the coefficients to understand the effect of each predictor on lwage</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pay special attention to the predictors with non-linear terms (e.g., I(predictor1^2))</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assess the model's overall fit (e.g., R-squared) and individual predictors' significance (p-values)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The linear regression model demonstrates that experience, blue-collar job status, living in an SMSA, marital status, gender, and race significantly impact the logarithm of wages. Specifically, experience, being in an SMSA, and being married are associated with higher wages, while being in a blue-collar job or being black is linked to lower wages. Gender also plays a crucial role, with males earning significantly more than females, all else being equal. Although the model explains about 31.82% of the variability in log wages, suggesting it captures key factors affecting wages, there remains a substantial portion of the variability unexplained, indicating potential for model improvement or the existence of other influential factors not included in the model.</p>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">b)</h2>
<p>The prediction model, with a Multiple R-squared of 0.3182, indicates that it can explain a moderate proportion of the variance in logarithmic wages based on the predictors used, though a significant amount of variability remains unaccounted for. The Residual Standard Error (RSE) of 0.3814 points to the average deviation of the observed values from the fitted values, suggesting the model’s predictions are reasonably close to the actual data, but there’s room for improvement. The significant p-values for all predictors confirm their relevance in explaining wage differences, ensuring that the model’s insights are statistically robust. However, to enhance predictive accuracy and account for more variance in wages, exploring additional predictors, interaction terms, or non-linear relationships could be beneficial.</p>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">c)</h2>
<p>This R function f implements a basic version of the k-Nearest Neighbors (k-NN) algorithm for regression. Here’s a line-by-line explanation:</p>
<p>f=function(x0,x,y,K=20): Defines a function f with inputs x0 (a new data point for which we want to predict the outcome), x (the matrix of features for the training data), y (the vector of outcomes for the training data), and K=20 (the number of nearest neighbors to consider, with a default value of 20).</p>
<p>n &lt;- nrow(x): Determines the number of observations in the training data by counting the rows in x.</p>
<p>p &lt;- ncol(x): Determines the number of features (predictors) in the training data by counting the columns in x.</p>
<p>d &lt;- matrix(0,n,1): Initializes a matrix d with n rows and 1 column filled with zeros. This is a placeholder for the distances between the new data point x0 and each point in the training data x.</p>
<p>d &lt;- sqrt(apply((x-matrix(x0,n,p,byrow=TRUE))^2,1,sum)): Calculates the Euclidean distance between x0 and each observation in x. This is done by subtracting x0 from each row in x (broadcasting x0 across n rows), squaring the differences, summing these squared differences across columns (apply(…,1,sum)), and taking the square root of these sums.</p>
<p>o &lt;- order(d)[1:K]: Orders the distances d in ascending order and selects the indices of the K smallest distances. These indices correspond to the K nearest neighbors of x0 in the training data.</p>
<p>ypred &lt;- mean(y[o]): Calculates the mean outcome y of the K nearest neighbors identified in the previous step. This mean value serves as the prediction for the new data point x0.</p>
<p>return(ypred): Returns the predicted outcome for the new data point x0.</p>
<p>In summary, this function implements the k-Nearest Neighbors algorithm for regression, predicting the outcome for a new observation based on the average outcome of its K nearest neighbors in the feature space.</p>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">d)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correcting the function f</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(x0, x, y, <span class="at">K =</span> <span class="dv">20</span>) {</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, n, <span class="dv">1</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">apply</span>((x <span class="sc">-</span> <span class="fu">matrix</span>(x0, n, p, <span class="at">byrow =</span> <span class="cn">TRUE</span>))<span class="sc">^</span><span class="dv">2</span>, <span class="dv">1</span>, sum))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  o <span class="ot">&lt;-</span> <span class="fu">order</span>(d)[<span class="dv">1</span><span class="sc">:</span>K]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  ypred <span class="ot">&lt;-</span> <span class="fu">mean</span>(y[o])</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(ypred)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Encoding 'sex' as a numeric variable where male = 1 and female = 0</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>Wages<span class="sc">$</span>sex_numeric <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(Wages<span class="sc">$</span>sex <span class="sc">==</span> <span class="st">"male"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Splitting the dataset into training and test sets</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># For reproducibility</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Wages), <span class="at">size =</span> <span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(Wages), <span class="at">replace =</span> <span class="cn">FALSE</span>) <span class="co"># 80% for training</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> Wages[indices, ]</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> Wages[<span class="sc">-</span>indices, ]</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the chosen predictors ('sex_numeric' and 'ed') and the target variable</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train_data[, <span class="fu">c</span>(<span class="st">"sex_numeric"</span>, <span class="st">"ed"</span>)])</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train_data<span class="sc">$</span>lwage</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(test_data[, <span class="fu">c</span>(<span class="st">"sex_numeric"</span>, <span class="st">"ed"</span>)])</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> test_data<span class="sc">$</span>lwage</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize vectors to store predictions</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>predictions_k10 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(y_test))</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>predictions_k20 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(y_test))</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop over the test set for K = 10 and K = 20</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(x_test)) {</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>  predictions_k10[i] <span class="ot">&lt;-</span> <span class="fu">f</span>(<span class="at">x0 =</span> x_test[i, ], <span class="at">x =</span> x_train, <span class="at">y =</span> y_train, <span class="at">K =</span> <span class="dv">10</span>)</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>  predictions_k20[i] <span class="ot">&lt;-</span> <span class="fu">f</span>(<span class="at">x0 =</span> x_test[i, ], <span class="at">x =</span> x_train, <span class="at">y =</span> y_train, <span class="at">K =</span> <span class="dv">20</span>)</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the predictions using Mean Squared Error (MSE)</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>mse_k10 <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_k10 <span class="sc">-</span> y_test)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>mse_k20 <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_k20 <span class="sc">-</span> y_test)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSE for K=10:"</span>, mse_k10))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE for K=10: 0.156565330368002"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSE for K=20:"</span>, mse_k20))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE for K=20: 0.14880810005982"</code></pre>
</div>
</div>
</section>
<section id="e" class="level2">
<h2 class="anchored" data-anchor-id="e">e)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function for k-fold cross-validation on the k-NN model</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>cross_validate_knn <span class="ot">&lt;-</span> <span class="cf">function</span>(K, folds, x, y) {</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  fold_size <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x) <span class="sc">/</span> folds</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  mse_list <span class="ot">&lt;-</span> <span class="fu">numeric</span>(folds)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>folds) {</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define indices for the validation set</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    val_indices <span class="ot">&lt;-</span> (((i <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> fold_size <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(i <span class="sc">*</span> fold_size))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Split the data into training and validation sets</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    x_train_cv <span class="ot">&lt;-</span> x[<span class="sc">-</span>val_indices, ]</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    y_train_cv <span class="ot">&lt;-</span> y[<span class="sc">-</span>val_indices]</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    x_val_cv <span class="ot">&lt;-</span> x[val_indices, ]</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    y_val_cv <span class="ot">&lt;-</span> y[val_indices]</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Predict using the current value of K</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    predictions <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(x_val_cv), <span class="cf">function</span>(j) <span class="fu">f</span>(<span class="at">x0 =</span> x_val_cv[j, ], <span class="at">x =</span> x_train_cv, <span class="at">y =</span> y_train_cv, <span class="at">K =</span> K))</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MSE for the current fold and store it</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    mse_list[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions <span class="sc">-</span> y_val_cv)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return the average MSE across all folds</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">mean</span>(mse_list))</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Range of K values to test</span></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>K_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">15</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="dv">2</span>)  <span class="co"># Testing K values from 1 to 30, skipping by 2</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="dv">3</span>  <span class="co"># Number of folds in k-fold cross-validation</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare the matrix of predictors and the target variable from the training data</span></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>x_train_cv <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train_data[, <span class="fu">c</span>(<span class="st">"sex_numeric"</span>, <span class="st">"ed"</span>)])</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>y_train_cv <span class="ot">&lt;-</span> train_data<span class="sc">$</span>lwage</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average MSE for each K</span></span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>mse_results <span class="ot">&lt;-</span> <span class="fu">sapply</span>(K_values, <span class="cf">function</span>(K) <span class="fu">cross_validate_knn</span>(K, folds, x_train_cv, y_train_cv))</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the optimal K with the lowest MSE</span></span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>optimal_K <span class="ot">&lt;-</span> K_values[<span class="fu">which.min</span>(mse_results)]</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>optimal_MSE <span class="ot">&lt;-</span> <span class="fu">min</span>(mse_results)</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Optimal K:"</span>, optimal_K))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Optimal K: 29"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Optimal MSE:"</span>, optimal_MSE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Optimal MSE: 0.164698507305595"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can then use this optimal K to make predictions and evaluate them as before</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="f" class="level2">
<h2 class="anchored" data-anchor-id="f">f)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'train_data' and 'test_data' are already defined</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train_data[, <span class="fu">c</span>(<span class="st">"sex_numeric"</span>, <span class="st">"ed"</span>)])</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train_data<span class="sc">$</span>lwage</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(test_data[, <span class="fu">c</span>(<span class="st">"sex_numeric"</span>, <span class="st">"ed"</span>)])</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> test_data<span class="sc">$</span>lwage</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># For LASSO</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># For reproducibility</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>cv_lasso <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># For Ridge Regression</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>cv_ridge <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions for LASSO</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>predictions_lasso <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv_lasso, <span class="at">newx =</span> x_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions for Ridge</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>predictions_ridge <span class="ot">&lt;-</span> <span class="fu">predict</span>(cv_ridge, <span class="at">newx =</span> x_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MSE</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>mse_lasso <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_lasso <span class="sc">-</span> y_test)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>mse_ridge <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_ridge <span class="sc">-</span> y_test)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"LASSO MSE:"</span>, mse_lasso))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LASSO MSE: 0.150351729238396"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Ridge MSE:"</span>, mse_ridge))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Ridge MSE: 0.150565228936139"</code></pre>
</div>
</div>
</section>
<section id="g" class="level2">
<h2 class="anchored" data-anchor-id="g">g)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the GAM</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>gam_model <span class="ot">&lt;-</span> <span class="fu">gam</span>(lwage <span class="sc">~</span> <span class="fu">s</span>(ed) <span class="sc">+</span> sex_numeric, <span class="at">data =</span> train_data)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gam_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
lwage ~ s(ed) + sex_numeric

Parametric coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6.25895    0.02036  307.42   &lt;2e-16 ***
sex_numeric  0.47088    0.02165   21.75   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
        edf Ref.df     F p-value    
s(ed) 2.331  2.905 230.8  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.254   Deviance explained = 25.5%
GCV = 0.15929  Scale est. = 0.15908   n = 3332</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>predictions_gam <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MSE</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>mse_gam <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_gam <span class="sc">-</span> test_data<span class="sc">$</span>lwage)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"GAM MSE:"</span>, mse_gam))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "GAM MSE: 0.149868440980557"</code></pre>
</div>
</div>
</section>
<section id="h" class="level2">
<h2 class="anchored" data-anchor-id="h">h)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using 'lwage' as the response variable and 'sex_numeric' and 'ed' as predictors</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>tree_model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(lwage <span class="sc">~</span> sex_numeric <span class="sc">+</span> ed, <span class="at">data=</span>train_data, <span class="at">method=</span><span class="st">"anova"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(tree_model, <span class="at">type=</span><span class="dv">4</span>, <span class="at">extra=</span><span class="dv">101</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Making predictions on the test set</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>predictions_tree <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree_model, <span class="at">newdata=</span>test_data)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the predictions, e.g., using Mean Squared Error (MSE)</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>mse_tree <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_tree <span class="sc">-</span> test_data<span class="sc">$</span>lwage)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSE for the tree:"</span>, mse_tree))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE for the tree: 0.153347527679205"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prune the tree</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>pruned_tree <span class="ot">&lt;-</span> <span class="fu">prune</span>(tree_model, <span class="at">cp=</span>tree_model<span class="sc">$</span>cptable[<span class="fu">which.min</span>(tree_model<span class="sc">$</span>cptable[,<span class="st">"xerror"</span>]),<span class="st">"CP"</span>])</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the pruned tree</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(pruned_tree, <span class="at">type=</span><span class="dv">4</span>, <span class="at">extra=</span><span class="dv">101</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the pruned tree's predictions</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>predictions_pruned <span class="ot">&lt;-</span> <span class="fu">predict</span>(pruned_tree, <span class="at">newdata=</span>test_data)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>mse_pruned <span class="ot">&lt;-</span> <span class="fu">mean</span>((predictions_pruned <span class="sc">-</span> test_data<span class="sc">$</span>lwage)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"MSE for the pruned tree:"</span>, mse_pruned))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MSE for the pruned tree: 0.153347527679205"</code></pre>
</div>
</div>
</section>
</section>
<section id="problem-2" class="level1">
<h1>Problem 2</h1>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">a)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the 75th percentile of lwage (log wage)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>lwage_75th_percentile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(Wages<span class="sc">$</span>lwage, <span class="fl">0.75</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new binary variable indicating whether an individual is in the top 25% of earners</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>Wages<span class="sc">$</span>top_25_earner <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(Wages<span class="sc">$</span>lwage <span class="sc">&gt;</span> lwage_75th_percentile, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>Wages <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,165
Columns: 14
$ exp           &lt;int&gt; 3, 4, 5, 6, 7, 8, 9, 30, 31, 32, 33, 34, 35, 36, 6, 7, 8…
$ wks           &lt;int&gt; 32, 43, 40, 39, 42, 35, 32, 34, 27, 33, 30, 30, 37, 30, …
$ bluecol       &lt;fct&gt; no, no, no, no, no, no, no, yes, yes, yes, yes, yes, yes…
$ ind           &lt;int&gt; 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ south         &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, no, no, no, no, no, n…
$ smsa          &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, …
$ married       &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, y…
$ sex           &lt;fct&gt; male, male, male, male, male, male, male, male, male, ma…
$ union         &lt;fct&gt; no, no, no, no, no, no, no, no, no, yes, no, no, no, no,…
$ ed            &lt;int&gt; 9, 9, 9, 9, 9, 9, 9, 11, 11, 11, 11, 11, 11, 11, 12, 12,…
$ black         &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, …
$ lwage         &lt;dbl&gt; 5.56068, 5.72031, 5.99645, 5.99645, 6.06146, 6.17379, 6.…
$ sex_numeric   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ top_25_earner &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">b)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Continuous variables</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>continuous_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"exp"</span>, <span class="st">"wks"</span>, <span class="st">"ed"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorical variables</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bluecol"</span>, <span class="st">"ind"</span>, <span class="st">"south"</span>, <span class="st">"smsa"</span>, <span class="st">"married"</span>, <span class="st">"sex"</span>, <span class="st">"union"</span>, <span class="st">"black"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty list to store plots for continuous and categorical variables</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plots_list_continuous <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>plots_list_categorical <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots for continuous variables</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(var <span class="cf">in</span> continuous_vars) {</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  plots_list_continuous[[var]] <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Wages, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(top_25_earner), <span class="at">y =</span> .data[[var]])) <span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(var, <span class="st">"by Top 25% Earners"</span>), <span class="at">x =</span> <span class="st">"Top 25% Earner"</span>, <span class="at">y =</span> var)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate plots for categorical variables</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(var <span class="cf">in</span> categorical_vars) {</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>  plots_list_categorical[[var]] <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Wages, <span class="fu">aes</span>(<span class="at">x =</span> .data[[var]], <span class="at">fill =</span> <span class="fu">as.factor</span>(top_25_earner))) <span class="sc">+</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Proportion of Top 25% Earners by"</span>, var), <span class="at">x =</span> var, <span class="at">y =</span> <span class="st">"Proportion"</span>) <span class="sc">+</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"gray"</span>, <span class="st">"blue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not Top 25% Earner"</span>, <span class="st">"Top 25% Earner"</span>))</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine and display the plots for continuous variables</span></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>combined_plot_continuous <span class="ot">&lt;-</span> <span class="fu">wrap_plots</span>(plots_list_continuous, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>combined_plot_continuous</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine and display the plots for categorical variables</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>combined_plot_categorical <span class="ot">&lt;-</span> <span class="fu">wrap_plots</span>(plots_list_categorical, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>combined_plot_categorical</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When analyzing binary variables, I consider the proportion differences between top 25% earners and non-top 25% earners for each variable. When analyzing binary variables, I consider the proportion differences between top 25% earners and non-top 25% earners for each variable. Predictors, where one of the categories has a much higher or lower proportion of top earners, could be more informative. By analyzing the plots, I want to move forward with the following predictors: bluecol married sex black Ed Exp</p>
</section>
<section id="c-1" class="level2">
<h2 class="anchored" data-anchor-id="c-1">c)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># For reproducibility</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Splitting the data into training and test sets</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>splitIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(Wages<span class="sc">$</span>top_25_earner, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>, <span class="at">times =</span> <span class="dv">1</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>trainData <span class="ot">&lt;-</span> Wages[splitIndex,]</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>testData <span class="ot">&lt;-</span> Wages[<span class="sc">-</span>splitIndex,]</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the formula for the logistic regression model</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>formula <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="st">"top_25_earner ~ bluecol + married + sex + black + ed + exp"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a logistic regression model using the defined formula</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>logitModel <span class="ot">&lt;-</span> <span class="fu">glm</span>(formula, <span class="at">data =</span> trainData, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logitModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = formula, family = "binomial", data = trainData)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -6.597602   0.444071 -14.857  &lt; 2e-16 ***
bluecolyes  -0.568331   0.114467  -4.965 6.87e-07 ***
marriedyes   0.112384   0.170875   0.658 0.510733    
sexmale      2.144859   0.309630   6.927 4.29e-12 ***
blackyes    -0.824375   0.239138  -3.447 0.000566 ***
ed           0.201334   0.021665   9.293  &lt; 2e-16 ***
exp          0.048559   0.004166  11.655  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3729.7  on 3331  degrees of freedom
Residual deviance: 3191.4  on 3325  degrees of freedom
AIC: 3205.4

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on the test set</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>predicted_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(logitModel, <span class="at">newdata =</span> testData, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>predicted_classes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probs <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>confusionMatrix <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> predicted_classes, <span class="at">Actual =</span> testData<span class="sc">$</span>top_25_earner)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusionMatrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 578 163
        1  39  53</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusionMatrix)) <span class="sc">/</span> <span class="fu">sum</span>(confusionMatrix)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Accuracy:"</span>, accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Accuracy: 0.75750300120048"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>TP_logit <span class="ot">&lt;-</span> confusionMatrix[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>FP_logit <span class="ot">&lt;-</span> confusionMatrix[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>FN_logit <span class="ot">&lt;-</span> confusionMatrix[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>TN_logit <span class="ot">&lt;-</span> confusionMatrix[<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>precision_logit <span class="ot">&lt;-</span> TP_logit <span class="sc">/</span> (TP_logit <span class="sc">+</span> FP_logit)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>recall_logit <span class="ot">&lt;-</span> TP_logit <span class="sc">/</span> (TP_logit <span class="sc">+</span> FN_logit)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>f1_score_logit <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (precision_logit <span class="sc">*</span> recall_logit) <span class="sc">/</span> (precision_logit <span class="sc">+</span> recall_logit)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Logistic Regression - Precision:"</span>, precision_logit, <span class="st">"Recall:"</span>, recall_logit, <span class="st">"F1 Score:"</span>, f1_score_logit, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic Regression - Precision: 0.2453704 Recall: 0.576087 F1 Score: 0.3441558 </code></pre>
</div>
</div>
<p>The model efficiently identifies people not in the top 25% of earners. Although the model’s accuracy is approximately 75.75%, which gives a general idea of its performance, it only partially represents its effectiveness, especially in the case of an imbalanced dataset. While the model shows a reasonable ability to detect non-top 25% earners (as indicated by a high number of true negatives), its precision is relatively low, which suggests a challenge in identifying the top 25% earners accurately without mistakenly classifying non-top 25% earners as being in the top quartile. The recall rate indicates that the model is better at capturing actual top 25% earners, but the balance between precision and recall shows that there is still room for improvement. Therefore, even though the model efficiently determines non-top 25% earners, it needs improvement in accurately identifying the top 25% earners.</p>
</section>
<section id="d-1" class="level2">
<h2 class="anchored" data-anchor-id="d-1">d)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co"># For lda function</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming testData and trainData from previous step are still valid</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Linear Discriminant Analysis</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>ldaModel <span class="ot">&lt;-</span> <span class="fu">lda</span>(formula, <span class="at">data =</span> trainData)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on the test set</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>ldaPred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ldaModel, <span class="at">newdata =</span> testData)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>predicted_classes_lda <span class="ot">&lt;-</span> ldaPred<span class="sc">$</span>class</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>confusionMatrixLDA <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> predicted_classes_lda, <span class="at">Actual =</span> testData<span class="sc">$</span>top_25_earner)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusionMatrixLDA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 578 165
        1  39  51</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>accuracyLDA <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusionMatrixLDA)) <span class="sc">/</span> <span class="fu">sum</span>(confusionMatrixLDA)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"LDA Accuracy:"</span>, accuracyLDA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LDA Accuracy: 0.755102040816326"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>TP_lda <span class="ot">&lt;-</span> confusionMatrixLDA[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>FP_lda <span class="ot">&lt;-</span> confusionMatrixLDA[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>FN_lda <span class="ot">&lt;-</span> confusionMatrixLDA[<span class="dv">2</span>, <span class="dv">1</span>]</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>TN_lda <span class="ot">&lt;-</span> confusionMatrixLDA[<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>precision_lda <span class="ot">&lt;-</span> TP_lda <span class="sc">/</span> (TP_lda <span class="sc">+</span> FP_lda)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>recall_lda <span class="ot">&lt;-</span> TP_lda <span class="sc">/</span> (TP_lda <span class="sc">+</span> FN_lda)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>f1_score_lda <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (precision_lda <span class="sc">*</span> recall_lda) <span class="sc">/</span> (precision_lda <span class="sc">+</span> recall_lda)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"LDA - Precision:"</span>, precision_lda, <span class="st">"Recall:"</span>, recall_lda, <span class="st">"F1 Score:"</span>, f1_score_lda, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LDA - Precision: 0.2361111 Recall: 0.5666667 F1 Score: 0.3333333 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Logistic Regression"</span>, <span class="st">"LDA"</span>),</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accuracy =</span> <span class="fu">c</span>(accuracy, accuracyLDA),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Precision =</span> <span class="fu">c</span>(precision_logit, precision_lda),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Recall =</span> <span class="fu">c</span>(recall_logit, recall_lda),</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">F1_Score =</span> <span class="fu">c</span>(f1_score_logit, f1_score_lda)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the comparison table</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comparison_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Model accuracy Precision    Recall  F1_Score
1 Logistic Regression 0.757503 0.2453704 0.5760870 0.3441558
2                 LDA 0.755102 0.2361111 0.5666667 0.3333333</code></pre>
</div>
</div>
<p>The table presented above displays the outcome of the LDA prediction and compares it with logistic regression. In comparison to logistic regression, we observe slightly adverse marginal effects. All measures of accuracy, precision, recall, and F1 score have decreased.</p>
<p>The decrease in these metrics for LDA suggests that, overall, it is performing slightly worse than Logistic Regression on this dataset. However, the differences are marginal, which means that in this specific case, both models are comparable in predicting the top 25% of earners, with Logistic Regression having a slight edge.</p>
<p>LDA assumes that the predictor variables are normally distributed, have the same variance-covariance matrix across each group, have a linear relationship with the discriminant function, are statistically independent of each other, and the dependent variable is categorical and discrete. LDA also requires an adequate sample size, absence of outliers, and linearity between the means of different groups. In some instances, the underlying assumptions are not properly met, which is the cause of the lesser performance.</p>
</section>
<section id="e-1" class="level2">
<h2 class="anchored" data-anchor-id="e-1">e)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)       <span class="co"># For building the classification tree</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)  <span class="co"># For plotting the tree</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a classification tree model</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>treeModel <span class="ot">&lt;-</span> <span class="fu">rpart</span>(formula, <span class="at">data =</span> trainData, <span class="at">method =</span> <span class="st">"class"</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the tree</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(treeModel, <span class="at">main =</span> <span class="st">"Classification Tree for Top 25% Earners"</span>, <span class="at">type =</span> <span class="dv">4</span>, <span class="at">extra =</span> <span class="dv">101</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BAN404_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on the test set</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>treePred <span class="ot">&lt;-</span> <span class="fu">predict</span>(treeModel, <span class="at">newdata =</span> testData, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>confusionMatrixTree <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> treePred, <span class="at">Actual =</span> testData<span class="sc">$</span>top_25_earner)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusionMatrixTree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 567 160
        1  50  56</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>accuracyTree <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusionMatrixTree)) <span class="sc">/</span> <span class="fu">sum</span>(confusionMatrixTree)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Tree Accuracy:"</span>, accuracyTree))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tree Accuracy: 0.747899159663866"</code></pre>
</div>
</div>
<p>We observe that the accuracy of the model is not as good as that of LDA and Logistic Regression.</p>
<p>The classification tree visually represents the decision rules inferred from the data. The nodes represent the points where the dataset is split based on the values of the predictor variables:</p>
<p>The root node (the topmost node) splits on the ‘ed’ variable, representing individuals’ education levels. If an individual’s education level is less than 14 years, they are more likely not to be among the top 25% earners (as seen in the large proportion of the class labeled ‘0’ in this node).</p>
<p>Following the tree to the right, if an individual has 14 or more years of education, further splits are done based on ‘exp’ (years of experience), ‘sex’, and ‘blue col’ (whether they are blue-collar workers), each refining the classification of an individual as a top 25% earner or not.</p>
<p>The leaf nodes (the bottom nodes) show the classification outcomes with the proportion of observations in each class. For example, one of the leaf nodes indicates that males with more than 17 years of experience and less than 38 years of experience, who are not blue-collar workers, are predicted to be top 25% earners.</p>
<section id="session-info" class="level4">
<h4 class="anchored" data-anchor-id="session-info">Session info</h4>
<p>Leave this part unchanged. The cell below prints which packages and versions were used for creating the html-file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Oslo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] patchwork_1.1.3      randomForest_4.7-1.1 MASS_7.3-60         
 [4] rpart.plot_3.1.1     rpart_4.1.21         mgcv_1.8-42         
 [7] nlme_3.1-162         glmnet_4.1-8         Matrix_1.6-1        
[10] caret_6.0-94         lattice_0.21-8       dplyr_1.1.4         
[13] ggplot2_3.4.4        Ecdat_0.4-2          Ecfun_0.3-2         

loaded via a namespace (and not attached):
 [1] bitops_1.0-7         pROC_1.18.4          inline_0.3.19       
 [4] rlang_1.1.1          magrittr_2.0.3       compiler_4.3.1      
 [7] vctrs_0.6.4          reshape2_1.4.4       rvest_1.0.3         
[10] stringr_1.5.0        pkgconfig_2.0.3      shape_1.4.6         
[13] fastmap_1.1.1        labeling_0.4.2       utf8_1.2.3          
[16] deSolve_1.40         rmarkdown_2.24       prodlim_2023.08.28  
[19] pracma_2.4.4         purrr_1.0.2          xfun_0.40           
[22] jsonlite_1.8.7       recipes_1.0.8        jpeg_0.1-10         
[25] parallel_4.3.1       cluster_2.1.4        R6_2.5.1            
[28] stringi_1.7.12       parallelly_1.36.0    rainbow_3.8         
[31] rrcov_1.7-5          lubridate_1.9.2      Rcpp_1.0.11         
[34] iterators_1.0.14     knitr_1.43           future.apply_1.11.0 
[37] hdrcde_3.4           splines_4.3.1        nnet_7.3-19         
[40] timechange_0.2.0     tidyselect_1.2.0     rstudioapi_0.15.0   
[43] yaml_2.3.7           timeDate_4022.108    codetools_0.2-19    
[46] listenv_0.9.0        tibble_3.2.1         plyr_1.8.9          
[49] ks_1.14.2            withr_2.5.0          evaluate_0.21       
[52] future_1.33.0        survival_3.5-5       xml2_1.3.5          
[55] mclust_6.1           pillar_1.9.0         fda_6.1.8           
[58] TeachingDemos_2.13   KernSmooth_2.23-21   foreach_1.5.2       
[61] stats4_4.3.1         pcaPP_2.0-4          generics_0.1.3      
[64] RCurl_1.98-1.14      munsell_0.5.0        scales_1.2.1        
[67] globals_0.16.2       leaps_3.1            class_7.3-22        
[70] glue_1.6.2           tools_4.3.1          fds_1.8             
[73] robustbase_0.99-0    data.table_1.14.8    ModelMetrics_1.2.2.2
[76] gower_1.0.1          mvtnorm_1.2-3        grid_4.3.1          
[79] ipred_0.9-14         colorspace_2.1-0     cli_3.6.1           
[82] fansi_1.0.4          lava_1.7.2.1         BMA_3.18.17         
[85] gtable_0.3.3         DEoptimR_1.1-2       digest_0.6.33       
[88] farver_2.1.1         htmlwidgets_1.6.2    htmltools_0.5.6     
[91] lifecycle_1.0.3      hardhat_1.3.0        httr_1.4.7          </code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>